import type { Metadata } from "next";
import "./../globals.css";
import Footer from "@/components/blocks/Footer";
import { ppEditorialNewUltralightItalic, inter } from "./../fonts";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/authOptions";
import SessionProviderClientComponent from "../(auth)/SessionProviderClientComponent";
import { CartProvider } from "@/components/cart-provider";
import { Header } from "@/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en" className={`${ppEditorialNewUltralightItalic.variable} ${inter.variable}`}>
      <body>
        <SessionProviderClientComponent session={session}>
          <CartProvider>
            <div className="flex flex-col min-h-screen">
              <Header />
              <main className="flex-1">{children}</main>
              <Footer />
            </div>
          </CartProvider>
        </SessionProviderClientComponent>
      </body>
    </html>
  );
}
