import type { Metadata } from "next";
import "./../globals.css";
import { SessionProviderClientComponent } from "../(auth)/SessionProviderClientComponent";
import { CartProvider } from "@/components/cart-provider";
import { Noto_Sans_Old_Persian } from "next/font/google";
import FooterSection from "@/components/footer-section";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const imffcs = Noto_Sans_Old_Persian({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-nsop",
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className={` ${imffcs.variable}`}>
      <body className={`dark`}>
        <SessionProviderClientComponent>
          <CartProvider>
            <main className="max-w-full ">{children}</main>
            <FooterSection />
          </CartProvider>
        </SessionProviderClientComponent>
      </body>
    </html>
  );
}
