import type { Metadata } from "next";
import "./../globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/authOptions";
import SessionProviderClientComponent from "../(auth)/SessionProviderClientComponent";
import { CartProvider } from "@/components/cart-provider";
import { Header } from "@/components/Header";
import { Noto_Sans_Old_Persian } from "next/font/google";
import FooterSection from "@/components/footer-section";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const imffcs = Noto_Sans_Old_Persian({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-nsop",
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en" className={` ${imffcs.variable}`}>
      <body className={`overflow-x-hidden ${imffcs.className}`}>
        <SessionProviderClientComponent session={session}>
          <CartProvider>
            <div className="relative flex flex-col">
              <Header />
              <main className="flex flex-col ">{children}</main>
              <FooterSection />
            </div>
          </CartProvider>
        </SessionProviderClientComponent>
      </body>
    </html>
  );
}

{
  /* <div className="min-h-screen flex flex-col">
              <Header />
              <main className="flex-1">{children}</main>
              <Footer />
            </div> */
}
