
import "../globals.css";
import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import { notFound, redirect } from "next/navigation";
import { auth } from "@/lib/auth";
import { headers } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const imffcs = Noto_Sans({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-imffcs",
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  const session = await auth.api.getSession({
    headers: headersList,
  })
  if (!session || !session.user.twoFactorEnabled || session.user.role !== "admin") {
    notFound();
  }

  return (
    <html lang="en" className="h-full">
      <body className={imffcs.className + " min-w-full max-w-full overflow-x-hidden "}>
        <h1>{session.user.email}</h1>
        {children}
      </body>
    </html>
  );
}
