import SessionProviderClientComponent from "@/app/(auth)/SessionProviderClientComponent";
import { authOptions } from "@/lib/authOptions";
import "../globals.css";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { GalleryVerticalEnd } from "lucide-react";
import AppConfig from "@/config/app-config";
import { Noto_Sans } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const imffcs = Noto_Sans({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-imffcs",
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en" className="h-full">
      <body className={imffcs.className}>{children}</body>
    </html>
  );
}
